### ISSUE TITLE
Uncaught TypeError: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by bparadie** [marcuswestin/store.js#125]
I am getting this error in the browser after minifying `store.js` with Google's closure compiler using `ADVANCED_OPTIMIZATIONS`:
```
Uncaught TypeError: Cannot read property 'module' of undefined
```

The offending code is `this.module` in this line:
```
if (typeof module != 'undefined' && module.exports && this.module !== module)
```

From what I can tell `this` is always the caller, which is `window`. Since the function is declared as  `function(win)` I suggest the following fix:
```
if (typeof module != 'undefined' && module.exports && win.module !== module)
```

You can see a far less elegant workaround in `gulpfile.js` of my repo:
https://github.com/bparadie/react-flux-typescript-todomvc

Removing that workaround will exhibit the problem.

**Comment by bachstatter** [comment]
I also get this error when I try to bundle with webpack

**Comment by bedeoverend** [comment]
+1 Getting the same issue with webpack

**Comment by bedeoverend** [comment]
Seems this issue has been fixed in master, install using `npm install marcuswestin/store.js#b11584` or `npm install marcuswestin/store.js#master` to get the lastest github.

**Comment by tsheaff** [comment]
@marcuswestin any solution to this yet.  Still an issue on latest 1.3.17 when requiring via webpack.

**Comment by MrBoolean** [comment]
Hmmm @marcuswestin: generate 1.3.18 to solve this.

**Comment by marcuswestin** [comment]
Fixed with v1.3.19 in c6c006eee1811.

I've been gone a long time. Really not appropriate as a maintainer. My bad guys, sorry for the long wait, thanks for all the patience, and I hope you'll all find good use of upcoming changes! (See https://github.com/marcuswestin/store.js/blob/master/Roadmap.md for details)
